---

- name: Disable ufw
  ansible.builtin.systemd:
    name: ufw
    state: stopped
    enabled: false
  when: disable_firewall is true

- name: Install openssl and iptables
  ansible.builtin.apt:
    name:
      - openssl
      - iptables
    state: present
    update_cache: true

- name: Load overlay kernel module
  ansible.builtin.command: modprobe overlay
  register: output
  changed_when: output.rc != 0

- name: Load br_netfilter kernel module
  ansible.builtin.command: modprobe br_netfilter
  register: output
  changed_when: output.rc != 0

- name: Load kernel modules - persistent
  ansible.builtin.blockinfile:
    path: /etc/modules-load.d/containerd.conf
    create: true
    mode: "0644"
    block: |
      overlay
      br_netfilter

- name: Modify sysctl parameters persistent
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    create: true
    mode: "0644"
    block: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Load br_netfilter kernel module
  ansible.builtin.command: sysctl --system
  register: output
  changed_when: output.rc != 0

- name: Check iptables version
  ansible.builtin.command: iptables --version
  register: iptables_version
  ignore_errors: true
  changed_when: iptables_version.stdout != 0

- name: Symlink for iptables
  community.general.alternatives:
    name: iptables
    link: /usr/sbin/iptables
    path: /usr/sbin/iptables-legacy

- name: Symlink for iptables
  community.general.alternatives:
    name: ip6tables
    link: /usr/sbin/ip6tables
    path: /usr/sbin/ip6tables-legacy

- name: Reboot initiated by Ansible for iptables-legacy
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for iptables-legacy"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: '"nf_tables" in iptables_version.stdout'
  ignore_errors: "{{ ansible_check_mode }}"
