resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    ---
    all:
      hosts:
        master-01:
          ansible_host: ${yandex_compute_instance.master-01.network_interface.0.nat_ip_address}
        worker-01:
          ansible_host: ${yandex_compute_instance.worker-01.network_interface.0.nat_ip_address}
        worker-02:
          ansible_host: ${yandex_compute_instance.worker-02.network_interface.0.nat_ip_address}
      children:
        k8s:
          children:
            k8s-init-master:
              hosts:
                master-01:
            k8s-workers:
              hosts:
                worker-01:
                worker-02:
      vars:
        ansible_connection_type: paramiko
        ansible_user: debian
        ansible_port: 22
        ansible_ssh_private_key_file: ../../../keys/id_rsa
    DOC
  filename = "../ansible/hosts-${terraform.workspace}.yml"

  depends_on = [
    yandex_compute_instance.master-01,
    yandex_compute_instance.worker-01,
    yandex_compute_instance.worker-02,
  ]
}
